name: hello_merge
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: merge
        run: |
          git fetch
          git checkout main
          git config --global user.email "58322558@qq.com"
          git config --global user.name "RegentZai"
          git merge --no-ff --allow-unrelated-histories dev
          git push origin main
