name: hello
on: 
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v3
    - name: hello
      run: chmod u+x hello.sh && ./hello.sh
    - name: merge
      env: GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout main
        git merge
        git push origin main -f
