name: hello
on: 
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v4
    - name: hello
      run: chmod u+x hello.sh && ./hello.sh
    - name: merge
      run: |
        git config --global user.name "RegentZai"
        git config --global user.email "58322558@qq.com"
        git config --global --unset https.proxy
        git config --global --unset http.proxy
        git fetch
        git checkout -b main2
        git checkout main
        git merge origin/main --allow-unrelated-histories
        git push origin main -f
        git branch -D main2
