name: hello
on: 
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v4
    - name: hello
      run: chmod u+x hello.sh && ./hello.sh
    - name: merge
      env:
        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
      run: |
        git config --global user.name "RegentZai"
        git config --global user.email "58322558@qq.com"
        git config --global --unset https.proxy
        git config --global --unset http.proxy
        git fetch
        git checkout main
        git merge dev --allow-unrelated histories
        git add .
        git commit
        git push origin main
