name: hello
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v3
    - name: hello
      run: chmod +x hello.sh && ./hello.sh
    - name: merge
      run: |
        git fetch
        git checkout origin/main
        git merge --allow-unrelated-histories -m "merge" dev
        git push --force main
