name: hello
on: 
  push:
    branches:
      - dev
jobs:
  build:
    steps:
      - runs-on: ubuntu:latest
      - name: hello
        run: chmod U+X hello.sh && ./hello.sh
      - name: merge
        run: |
          git checkout main
          git merge
          git push origin main -f
