name: Merge Dev to Main

on:
  push:
    branches: [dev]

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Merge dev to main
      env:
        GITHUB_TOKEN:  $${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout main
        git pull origin main
        git merge dev --no-edit --no-ff -m "Merge dev branch into main branch"
        git push origin main -f -u
