name: hello_merge
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: hello_and_merge
        run: |
          git fetch
          chmod +x hello.sh
          ./hello.sh 
          git checkout main
          git config --global user.email "2507836311@qq.com"
          git config --global user.name "kksk114"
          git merge --no-ff --allow-unrelated-histories dev
          git push
          git push origin main