name: hello
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v3
    - name: hello
      run: chmod +x hello.sh && ./hello.sh
    - name: merge
      env:
        github_token: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.name "RegentZai"
        git config --global user.email "58322558@qq.com"
        git fetch
        git status
        git checkout origin/main
        git merge --allow-unrelated-histories -m "merge" origin/dev
        git checkout origin/main
        git push --force origin main
